export const userActions = {
  SET_USERS: "SET_USERS",
  SELECT_ALL: "SELECT_ALL",
  DE_SELECT_ALL: "DE_SELECT_ALL",
  SELECT_USER: "SELECT_USER",
  DELETE_SELECTED: "DELETE_SELECTED",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  SET_PAGE: "SET_PAGE",
  NEXT_PAGE: "NEXT_PAGE",
  PREVIOUS_PAGE: "PREVIOUS_PAGE",
  SET_LOADING:"SET_LOADING"
};
